# adapted from ocaml_interop

[package]
name = "rustast_bindings"
version = "0.1.0"
authors = ["Aseem Rastogi"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
path = "rust/src/lib.rs"

[dependencies]
ocaml-interop = "0.9.2"
syn = { version="2.0.29", features=["full", "derive"] }
proc-macro2 = "1.0.66"
quote = "1.0.33"
prettyplease = "0.2.16"